[TASK] add support for php 8.x
pagemachine/typo3-formlog pull request #138
Opened 2022-03-10 08:07 UTC by lukasniestroj

* drop scable/xml-lint since it's not compatible with php 8.1
* use nimut/testing-framework:dev-main (6.0 is missing php 8.1 support)

2022-03-10 08:19 UTC, mbrodala requested changes

2022-03-10 08:19 UTC, mbrodala commented on .github/workflows/ci.yml
> +          - 8.1
This won't work, you'll need to add an extra matrix entry for TYPO3v11 + PHP 8 instead. Otherwise you'd also run [TYPO3v10 on PHP 8 which does not work](https://packagist.org/packages/typo3/cms-core#v10.4.26).

2022-03-10 08:19 UTC, mbrodala commented on composer.json
> +        "typo3/cms-core": "11.5",
First of all we'll keep TYPO3v10 support for now, so this is not an option. Then `11.5` should be `^11.5` instead. And finally you'd need to adjust all other `typo3/cms-*` dependencies too.

2022-03-10 08:19 UTC, mbrodala commented on composer.json
> +        "nimut/testing-framework": "^6.0 || dev-main",
I'd rather wait for a stable release, otherwise we are in for random failures.

2022-03-10 08:19 UTC, mbrodala commented on composer.json
> -        "sclable/xml-lint": "^0.4.0",
I'd rather wait for https://github.com/sclable/xml-lint/pull/25

2022-03-10 08:19 UTC, mbrodala commented on composer.json
> +        "php": "^7.4 || ^8.0",
You'd also need to adjust `ext_emconf.php`.

2022-03-10 09:13 UTC, lukasniestroj commented on .github/workflows/ci.yml
> +          - 8.1
I see!

2022-03-10 09:13 UTC, lukasniestroj commented on composer.json
> +        "typo3/cms-core": "11.5",
oh this was unintended.

2022-03-10 09:13 UTC, lukasniestroj commented on composer.json
> +        "php": "^7.4 || ^8.0",
thanks!

2022-03-25 13:17 UTC, lukasniestroj commented on composer.json
> -        "sclable/xml-lint": "^0.4.0",
updated to 0.5.0

2022-03-25 13:54 UTC, mbrodala commented on composer.json
> -        "sclable/xml-lint": "^0.4.0",
This is already in: https://github.com/pagemachine/typo3-formlog/pull/140

Please do a rebase on `master` for the latest state. :-)

2022-04-26 16:06 UTC, mbrodala commented
I just did this with https://github.com/pagemachine/typo3-formlog/pull/149 so thanks for the patience!

2022-04-26 16:06 UTC, closed without merging