[FEATURE] Save filenames of FileUploads
pagemachine/typo3-formlog pull request #59
Opened 2021-02-19 14:25 UTC by sabbelasichon

Resolves: #53

2021-02-25 15:32 UTC, mbrodala requested changes

2021-02-25 19:19 UTC, sabbelasichon commented on Classes/Domain/Form/Finishers/LoggerFinisher.php
> +    protected function addFileUploadsToFormValues(FormRuntime $formRuntime, array $formValues): array
They are already included, sure. But only as of value FileReference. In order to only save elements of type FileUpload we need to iterate over all the renderables of the original FormDefinition. But maybe we could just iterate over all formValues and check if one form value is of type FileReference. Sure. Makes more sense. New commit is coming.

2021-02-26 09:37 UTC, mbrodala requested changes

2021-02-26 09:37 UTC, mbrodala commented on Classes/Domain/Form/Finishers/LoggerFinisher.php
> +        /** @var \TYPO3\CMS\Core\Database\Connection; */
This is not really necessary I'd say. ;-)

2021-02-26 09:37 UTC, mbrodala commented on Classes/Domain/Form/Finishers/LoggerFinisher.php
> +            }
I'd suggest to move this to a `normalizeFormValues()` method. Since we are in the context of this finisher, there is no need to point out that the result is saved to the DB.

2021-02-26 09:37 UTC, mbrodala commented on Tests/Unit/Domain/Form/Finishers/LoggerFinisherTest.php
> +    public function logsFormValuesToDatabaseWithFileUpload()
Can you add a data provider instead so that the existing test covers this?

2021-03-02 09:57 UTC, mbrodala requested changes
We are almost there, thanks for the patience!

2021-03-02 09:57 UTC, mbrodala commented on Classes/Domain/Form/Finishers/LoggerFinisher.php
> +    private function isFileReference($formValue): bool
This should be embedded in the `normalizeFormValues()` method. Also this is missing an `is_object()` check.

2021-03-02 09:57 UTC, mbrodala commented on Tests/Unit/Domain/Form/Finishers/LoggerFinisherTest.php
> +use Iterator;
We never do something like this. Also this does not seem to be used at all.

2021-03-02 09:57 UTC, mbrodala commented on Tests/Unit/Domain/Form/Finishers/LoggerFinisherTest.php
> +     * @param array $finisherVariables
There is no need for these since we have real type hints already.

2021-03-02 09:57 UTC, mbrodala commented on Tests/Unit/Domain/Form/Finishers/LoggerFinisherTest.php
> +    public function logsFormValuesToDatabase(array $formValues, array $expectedData, FinisherVariableProvider $variableProvider, array $finisherVariables)
I don't see why we need a custom `$variableProvider`. Instead injecting the variables into the one from this test should be enough.

2021-03-02 09:57 UTC, mbrodala commented on Tests/Unit/Domain/Form/Finishers/LoggerFinisherTest.php
> -    public function addsFinisherVariables()
Please keep this test separated.

2021-03-04 08:14 UTC, sabbelasichon commented on Tests/Unit/Domain/Form/Finishers/LoggerFinisherTest.php
> +use Iterator;
The dataProvider returns a Generator. The Generator class itself is extending the Iterator class. So it is  a more generic approach. But to be consistent i added the Traversable docblock

2021-03-04 08:16 UTC, sabbelasichon commented on Tests/Unit/Domain/Form/Finishers/LoggerFinisherTest.php
> +    public function logsFormValuesToDatabase(array $formValues, array $expectedData, FinisherVariableProvider $variableProvider, array $finisherVariables)
It was needed because i added also the test addsFinisherVariables into the dataProvider. I have separated it again, so now it is not needed anymore.

2021-03-05 13:52 UTC, mbrodala approved these changes
Love it, thanks a lot!

2021-03-05 13:52 UTC, merged