[FEATURE] Add TYPO3 V11 Compatibility. Resolves #83
pagemachine/typo3-formlog pull request #84
Opened 2021-09-07 08:46 UTC by pulponair

There may be some visual glitches left in the Backend Module due to Bootstrap 5 vs 3. But everything is working

2021-09-10 09:36 UTC, mbrodala requested changes
Thanks for taking a first stab at it. I left a few remarks, mostly about actually staying compatible with TYPO3v10.

Aside from that the Github action for CI must be adjusted to also run for TYPO3v11.

Finally I'd strongly suggest to make as many meaningful small commits as possible instead of a huge single commit. This makes it a lot easier to understand each change and its reason and look up changes later.

2021-09-10 09:36 UTC, mbrodala commented on Classes/Controller/Backend/FormLogController.php
> +declare(strict_types=1);
We should keep the changes to the bare minimum, formatting should be done separately.

2021-09-10 09:36 UTC, mbrodala commented on Classes/Controller/Backend/FormLogController.php
> -/*
See above, this must be left unchanged.

2021-09-10 09:36 UTC, mbrodala commented on Classes/Controller/Backend/FormLogController.php
> +                ->allowAllProperties();
You know the drill. ;-)

2021-09-10 09:36 UTC, mbrodala commented on Classes/Controller/Backend/FormLogController.php
> +    public function indexAction(Filters $filters, int $currentPageNumber = 1): ResponseInterface
This will break backwards-compat with TYPO3v10 so we must skip this for now.

2021-09-10 09:36 UTC, mbrodala commented on Classes/Controller/Backend/FormLogController.php
> +        return $this->htmlResponse();
Here you need to check if the method is available at all which is not the case with TYPO3v10.

2021-09-10 09:36 UTC, mbrodala commented on Configuration/TCA/tx_formlog_entries.php
> -        'showRecordFieldList' => 'crdate, language, identifier, data',
This is indeed [obsolete but with TYPO3v10 already](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.3/Feature-88901-RenderAllFieldsInElementInformationController.html). So this should be done separately.

2021-09-10 09:36 UTC, mbrodala commented on Resources/Private/Partials/Backend/FormLog/ExportActions.html
> +      <button type="button" class="btn btn-default dropdown-toggle" data-bs-toggle="dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
See above, this breaks the functionality with TYPO3v10.

2021-09-10 09:36 UTC, mbrodala commented on composer.json
> -            "cms-package-dir": "{$vendor-dir}/typo3/cms",
You know the drill. ;-)

2021-09-10 09:42 UTC, mbrodala commented on Configuration/TCA/tx_formlog_entries.php
> -        'showRecordFieldList' => 'crdate, language, identifier, data',
Done now in https://github.com/pagemachine/typo3-formlog/pull/85

2021-09-10 13:05 UTC, pulponair commented
@mbrodala Hey thanks for having a look.
Regarding seperate commits:
Yes you are right, i did a final rebase because i had a lot back and forth commits in it.

Regarding formating: Well, i would slighly disagree. I actually don't format the code manually. I just hit ctrl+alt+L. 
Going through all formerly missformated lines manually and reverting em to "wrong" feels a little weired.
Especially seeing your CS Rules being pretty strict in contrast :).

Regarding Bootstrap:
I don't see how adding an and additonal data attribute for Bootstrap 5 is breaking things?. 
"data-bs-toggle" is not even known by BS3 afaik. Please enlight me.

2021-09-10 13:55 UTC, pulponair commented on Resources/Private/Partials/Backend/FormLog/ExportActions.html
> +      <button type="button" class="btn btn-default dropdown-toggle" data-bs-toggle="dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
@mbrodala Are you sure? I don't  see how data-bs-toggle should break anything. Afaik it is not even known to BS3. Enlight me :)

2021-09-10 13:55 UTC, pulponair commented on Classes/Controller/Backend/FormLogController.php
> +                ->allowAllProperties();
@mbrodala do you really want me to revert this?

2021-09-10 13:56 UTC, pulponair commented on composer.json
> -            "cms-package-dir": "{$vendor-dir}/typo3/cms",
@mbrodala do you really want me to revert this?

2021-09-13 15:27 UTC, mbrodala commented on Classes/Controller/Backend/FormLogController.php
> +                ->allowAllProperties();
Yes, please. It's there for a reason after all.

2021-09-13 15:28 UTC, mbrodala commented on Resources/Private/Partials/Backend/FormLog/ExportActions.html
> +      <button type="button" class="btn btn-default dropdown-toggle" data-bs-toggle="dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
Sure thing: https://getbootstrap.com/docs/3.4/javascript/#dropdowns

In Bootstrap 3.x you need to use `data-toggle="dropdown"`.

So in the simplest case we could maybe add both attributes to cover Bootstrap 3/4/5.

2021-09-13 15:28 UTC, mbrodala commented on composer.json
> -            "cms-package-dir": "{$vendor-dir}/typo3/cms",
Yes.

2021-09-14 15:52 UTC, pulponair commented on Resources/Private/Partials/Backend/FormLog/ExportActions.html
> +      <button type="button" class="btn btn-default dropdown-toggle" data-bs-toggle="dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
@mbrodala If you read carefully you will see that this is exactly what i did (having both data attributes)

2021-09-14 15:57 UTC, mbrodala commented on Resources/Private/Partials/Backend/FormLog/ExportActions.html
> +      <button type="button" class="btn btn-default dropdown-toggle" data-bs-toggle="dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
Ah indeed. Too used to multiline HTML for better Git diffs. ;-)

2021-09-14 16:03 UTC, pulponair commented on Classes/Controller/Backend/FormLogController.php
> +                ->allowAllProperties();
@mbrodala ok, what is the reason for a double indention in Method chaining? There is no official PSR nor cgl specifing double indention for method chaining. :) But anyway i ll remove it.

2021-09-14 16:13 UTC, mbrodala commented on Classes/Controller/Backend/FormLogController.php
> +                ->allowAllProperties();
In this case it's there to clearly show that the final `allowAllProperties()` works on a different object than the `forProperty()` before. Otherwise one who doesn't know about the fact that `forProperty()` returns a new object would be confused why there are two `allowAllProperties()` calls.

2021-09-14 16:18 UTC, pulponair commented on composer.json
> -            "cms-package-dir": "{$vendor-dir}/typo3/cms",
done

2021-09-21 07:41 UTC, mbrodala commented
(I'll be able to continue reviewing as early as at the end of next week.)

2021-09-29 10:59 UTC, mbrodala commented
It looks quite good but I noticed that the select filter fields are not shown anymore. Instead only the placeholder `...` is shown:

![image](https://user-images.githubusercontent.com/5037116/135255647-8cc98059-6837-4888-9a0e-d9601bb77c1f.png)

This is very likely related to the fact that popovers have a `.popover-body` with BS5 compared to a `.popover-content` with BS3. Can you incorporate that?

See https://github.com/pagemachine/typo3-formlog/blob/c11e90c6d192757b55c610949a9628a5508657b5/Resources/Private/JavaScript/FormLog/Filter/SelectFilter.js#L39

Also the pagination is missing some styling:

![image](https://user-images.githubusercontent.com/5037116/135255824-27c1fcd9-75dd-425f-a7c8-1a23759d368c.png)

2022-01-07 16:52 UTC, mbrodala commented
Thanks for getting this started, I took some inspiration and prepared https://github.com/pagemachine/typo3-formlog/pull/111 now. That one contains all necessary updates to have the extension working with TYPO3v11. It would be great if you could add your review there.

2022-01-07 16:52 UTC, closed without merging